add test which confirms that Quartz scheduler fails by default if its shared across two actors. test is failing with
[INFO] [09/23/2019 12:47:48.726] [ScalaTest-run] [[QuartzScheduler~QuartzFailOnSharingItByTwoActorsTest]] Initialized calendars:
[INFO] [09/23/2019 12:47:48.804] [QuartzFailOnSharingItByTwoActorsTest-akka.actor.default-dispatcher-2] [[QuartzScheduler~QuartzFailOnSharingItByTwoActorsTest]] Setting up scheduled job 'QuartzActor2_schedule1', with 'com.typesafe.akka.extension.quartz.QuartzCronSchedule@3884b5c5'
[ERROR] [09/23/2019 12:47:48.810] [QuartzFailOnSharingItByTwoActorsTest-akka.actor.default-dispatcher-5] [akka://QuartzFailOnSharingItByTwoActorsTest/user/$a] No matching quartz configuration found for schedule 'QuartzActor1_schedule1'
akka.actor.ActorInitializationException: akka://QuartzFailOnSharingItByTwoActorsTest/user/$a: exception during creation
	at akka.actor.ActorInitializationException$.apply(Actor.scala:193)
	at akka.actor.ActorCell.create(ActorCell.scala:669)
	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:523)
	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:545)
	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:283)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:235)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.IllegalArgumentException: No matching quartz configuration found for schedule 'QuartzActor1_schedule1'
	at com.typesafe.akka.extension.quartz.QuartzSchedulerExtension.scheduleInternal(QuartzSchedulerExtension.scala:370)
	at com.typesafe.akka.extension.quartz.QuartzSchedulerExtension.schedule(QuartzSchedulerExtension.scala:305)
	at pl.laron.tutorial.akka.quartz.QuartzActor1.<init>(QuartzActor1.scala:16)
	at pl.laron.tutorial.akka.quartz.QuartzFailOnSharingItByTwoActorsTest$$anonfun$1$$anonfun$apply$1.apply(QuartzFailOnSharingItByTwoActorsTest.scala:14)
	at pl.laron.tutorial.akka.quartz.QuartzFailOnSharingItByTwoActorsTest$$anonfun$1$$anonfun$apply$1.apply(QuartzFailOnSharingItByTwoActorsTest.scala:14)
	at akka.actor.TypedCreatorFunctionConsumer.produce(IndirectActorProducer.scala:87)
	at akka.actor.Props.newActor(Props.scala:212)
	at akka.actor.ActorCell.newActor(ActorCell.scala:624)
	at akka.actor.ActorCell.create(ActorCell.scala:650)
	... 9 more

The code passed to eventually never returned normally. Attempted 8 times over 160.950836 milliseconds. Last failure message:

assert(scheduler.runningJobs.size == 2)
       |         |           |    |  |
       |         |           1    |  2
       |         |                false
       |         Map("QuartzActor2_schedule1" -> DEFAULT.QuartzActor2_schedule1_Job)
       com.typesafe.akka.extension.quartz.QuartzSchedulerExtension@2bb3058